# TESTS ADMINISTERED {#sec-tests}

- Comprehensive Neurodevelopmental Symptom and History Interview
- Behavioral Assessment System for Children, 3rd ed, Structured Developmental History (BASC-3 SDH)
- KSADS
- Adaptive Behavior Assessment System, 3rd ed, Parent Form (ABAS-3 Parent)
- Adaptive Behavior Assessment System, 3rd ed, Parent/Primary Caregiver Form (ABAS-3 Parent)
- Adaptive Behavior Assessment System, 3rd ed, Self-Report Form (ABAS-3 Self)
- Adaptive Behavior Assessment System, 3rd ed, Teacher Form (ABAS-3 Teacher)
- Behavioral Assessment System for Children, 3rd ed, Parent Rating Scales, Adolescent (BASC-3 PRS Adolescent)
- Behavioral Assessment System for Children, 3rd ed, Parent Rating Scales, Child (BASC-3 PRS Child)
- Behavioral Assessment System for Children, 3rd ed, Parent Rating Scales, Preschool (BASC-3 PRS Preschool)
- Behavioral Assessment System for Children, 3rd ed, Self-Report of Personality, Adolescent (BASC-3 SRP Adolescent)
- Behavioral Assessment System for Children, 3rd ed, Self-Report of Personality, Child (BASC-3 SRP Child)
- Behavioral Assessment System for Children, 3rd ed, Teacher Rating Scales, Adolescent (BASC-3 TRS Adolescent)
- Behavioral Assessment System for Children, 3rd ed, Teacher Rating Scales, Child (BASC-3 TRS Child)
- Behavioral Assessment System for Children, 3rd ed, Teacher Rating Scales, Preschool (BASC-3 TRS Preschool)
- Bracken School Readiness Assessment, 4th ed (BSRA-4)
- Brown Executive Function/Attention Scales, Parent Report (Brown EF/A Parent)
- Brown Executive Function/Attention Scales, Self-Report (Brown EF/A Self)
- Brown Executive Function/Attention Scales, Teacher Report (Brown EF/A Teacher)
- California Verbal Learning Test, Child ed (CVLT-C)
- Childhood Autism Rating Scale, 2nd ed (CARS-2)
- Childhood Autism Rating Scale, 2nd ed, High-Functioning Version (CARS-2 HF)
- Childhood Autism Rating Scale, 2nd ed, Questionnaire for Parents or Caregivers (CARS-2 QPC)
- Children's Memory Scale, 3rd ed (CMS-3)
- Clinical Evaluation of Language Fundamentals Preschool, 3rd ed (CELF Preschool-3)
- Clinical Evaluation of Language Fundamentals, 5th ed, Ages 5-8 (CELF-5)
- Clinical Evaluation of Language Fundamentals, 5th ed, Ages 9-21 (CELF-5)
- Comprehensive Executive Function Inventory, Parent Report (CEFI Parent)
- Comprehensive Executive Function Inventory, Self-Report (CEFI Self)
- Comprehensive Executive Function Inventory, Teacher Report (CEFI Teacher)
- Comprehensive Executive Function Inventory, Youth Report (CEFI Youth)
- Comprehensive Neurodevelopmental Symptom and History Interview
- Conners' Rating Scale, 4th ed, Parent (Conners-4 Parent)
- Conners' Rating Scale, 4th ed, Self-Report (Conners-4 Self)
- Conners' Rating Scale, 4th ed, Teacher (Conners-4 Teacher)
- Delis-Kaplan Executive Function System (D-KEFS)
- Dot Counting Test (DCT)
- Grooved Pegboard Test
- Kaufman Test of Educational Achievement, 3rd ed, Form A (KTEA-3 Form A)
- Kaufman Test of Educational Achievement, 3rd ed, Form B (KTEA-3 Form B)
- NEPSY-II Developmental Neuropsychological Battery
- PROMIS Sleep Assessments Pediatric Parent Proxy
- Rating Scale of Impairment (RSI)
- Repeatable Battery for the Assessment of Neuropsychological Status, Form A (RBANS)
- Repeatable Battery for the Assessment of Neuropsychological Status, Form B (RBANS)
- Repeatable Battery for the Assessment of Neuropsychological Status, Form C (RBANS)
- Repeatable Battery for the Assessment of Neuropsychological Status, Form D (RBANS)
- Rey-Osterrieth Complex Figure Test (ROCFT)
- Trail Making Test (TMT)
- Wechsler Abbreviated Scale of Intelligence, 2nd ed (WASI-2)
- Wechsler Individual Achievement Test, 4th ed (WIAT-4)
- Wechsler Individual Achievement Test, 4th ed (WIAT-4): Word Reading, Reading Comprehension, Pseudoword Decoding, Orthographic Fluency, Decoding Fluency 
- Wechsler Intelligence Scale for Children, 5th ed (WISC-V)
- Wechsler Preschool and Primary Scale of Intelligence, 4th ed, Ages 2-3 (WPPSI-IV)
- Wechsler Preschool and Primary Scale of Intelligence, 4th ed, Ages 4-7 (WPPSI-IV)
- Personality Assessment Inventory, Adolescent (PAI-A)
- Wide Range Achievement Test, 5th ed (WRAT-5)
- Wide Range Achievement Test, 5th ed, Blue Form (WRAT-5): Word Reading
- Wide Range Achievement Test, 5th ed, Green Form (WRAT-5): Word Reading
- NIH Executive Abilities--Measures and Instruments for Neurobehavioral Evaluation and Research (NIH EXAMINER):
  - Behavioral Rating Scale
  - Word Fluency
  - Unstructured Task
