project:
  type: default
  title: "Pediatric Report"
  execute-dir: project
  render:
    - "!quarto/"
    - template.qmd

format:
  neurotyp-pediatric-typst:
    keep-typ: true
    keep-md: true
    papersize: "us-letter"
    bodyfont: "IBM Plex Serif"
    sansfont: "IBM Plex Sans"
    fontsize: 11pt
    number-sections: false
    number-offset: 1
    citeproc: true
    csl: inst/resources/bib/apa.csl
    shift-heading-level-by: 0
    fig-width: 6
    fig-height: 4
    fig-format: svg

execute:
  warning: false
  echo: false
  message: false
  freeze: auto
  cache: true
  engine: knitr
  tools:
    r: "/usr/local/bin/R"

editor:
  markdown:
    wrap: sentence
    canonical: true
fig-width: 6
fig-asp: 0.618
out-width: 70%
fig-align: center
fig-format: svg
fig-dpi: 270
df-print: kable
reference-location: document
bibliography: inst/resources/bib/refs.bib
